language: java
jdk: openjdk8
install: 
- mvn -N io.takari:maven:wrapper
cache:
  directories:
  - $HOME/.m2


after_success:
  - mvn evosuite:generate evosuite:export test jacoco:report org.eluder.coveralls:coveralls-maven-plugin:report clean 