language: java
jdk: openjdk8
install: 
- mvn -N io.takari:maven:wrapper
cache:
  directories:
  - $HOME/.m2
script:
- ./mvnw evosuite:generate
- ./mvnw evosuite:export
- ./mvnw clean install
- ./mvnw evosuite:info

after success:
- bash <(curl -s https://codecov.io/bash)