language: java
jdk: openjdk10
install: 
- mvn -N io.takari:maven:wrapper
- ./mvnw clean install
cache:
  directories:
  - $HOME/.m2
script:
- ./mvnw test
- curl -Os https://uploader.codecov.io/latest/linux/codecov
- chmod +x codecov
- ./codecov